# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecog',
            name='Value3',
            field=models.IntegerField(default=0),
        ),
    ]
