# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_ecog_value3'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecog',
            name='Value10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ecog',
            name='Value4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ecog',
            name='Value5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ecog',
            name='Value6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ecog',
            name='Value7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ecog',
            name='Value8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ecog',
            name='Value9',
            field=models.IntegerField(default=0),
        ),
    ]
